$(eval $(call addlib_s,libshfs,$(CONFIG_LIBSHFS)))

CINCLUDES-$(CONFIG_LIBSHFS)	+= -I$(LIBSHFS_BASE)/include
CXXINCLUDES-$(CONFIG_LIBSHFS)	+= -I$(LIBSHFS_BASE)/include

LIBSHFS_SRCS-y += $(LIBSHFS_BASE)/shfs_check.c
LIBSHFS_SRCS-y += $(LIBSHFS_BASE)/shfs.c
